const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
export function intelligenceConfidence(country={}){return clamp(.26+Number(country.intelligence||20)/100*.34+Number(country.techIntel||0)*.065+Number(country.army?.recon||0)*.008+Number(country.army?.drones||0)*.006+Number(country.satelliteRecon||0)*.035,.26,.97)}
function q(v,step){const n=Number(v||0);return Math.max(0,Math.round(n/step)*step)}
function redactArmy(a={},confidence=.4){const low=confidence<.48,mid=confidence<.72;return {...a,soldiers:q(a.soldiers,low?10:mid?5:2),tanks:q(a.tanks,low?4:mid?2:1),artillery:q(a.artillery,low?4:mid?2:1),airDefense:q(a.airDefense,low?3:mid?2:1),aircraft:q(a.aircraft,low?3:mid?2:1),helicopters:q(a.helicopters,low?3:mid?2:1),drones:q(a.drones,low?4:mid?2:1),recon:q(a.recon,low?3:mid?2:1),navy:q(a.navy,low?3:mid?2:1)} }
export function snapshotForObserver(snapshot,observerController){if(!snapshot||!observerController)return snapshot;const out=structuredClone(snapshot),countries=Object.values(out.countries||{}),observer=countries.find(c=>c.controller===observerController),confidence=observer?intelligenceConfidence(observer):.30,resourceStep=confidence<.48?25:confidence<.72?10:5;for(const c of countries){if(c.controller===observerController)continue;c.army=redactArmy(c.army,confidence);if(c.stock)for(const k of Object.keys(c.stock))c.stock[k]=q(c.stock[k],resourceStep);if(c.production)for(const k of Object.keys(c.production))c.production[k]=q(c.production[k],confidence<.48?5:2);c.stability=q(c.stability,confidence<.48?15:5);c.approval=q(c.approval,confidence<.48?15:5);c.supply=q(c.supply,confidence<.48?20:10);c.morale=q(c.morale,confidence<.48?20:10);c.missileStock=q(c.missileStock,confidence<.48?4:confidence<.72?2:1);c.cruiseMissiles=q(c.cruiseMissiles,confidence<.48?4:confidence<.72?2:1);c.ballisticMissiles=q(c.ballisticMissiles,confidence<.48?3:confidence<.72?2:1);c.hypersonicMissiles=q(c.hypersonicMissiles,confidence<.48?2:1);c.missileDefense=q(c.missileDefense,confidence<.48?2:1);c.missileProgram=q(c.missileProgram,confidence<.48?2:1);c.electronicWarfare=q(c.electronicWarfare,confidence<.48?2:1);c.satelliteRecon=q(c.satelliteRecon,confidence<.48?2:1);c.radarLevel=q(c.radarLevel,confidence<.48?2:1);c.earlyWarning=q(c.earlyWarning,confidence<.48?2:1);c.carrierStock=q(c.carrierStock,confidence<.48?2:1);c.submarineStock=q(c.submarineStock,confidence<.48?3:confidence<.72?2:1);c.airReadiness=q(c.airReadiness,confidence<.48?25:10);c.fleetReadiness=q(c.fleetReadiness,confidence<.48?25:10);}
for(const a of out.fieldArmies||[]){if(a.owner===observerController)continue;Object.assign(a,redactArmy(a,confidence));a.supply=q(a.supply,confidence<.48?25:10);a.morale=q(a.morale,confidence<.48?25:10)}
for(const p of out.provinces||[]){if(p.controller===observerController)continue;p.garrison=q(p.garrison,confidence<.48?10:5);p.supply=q(p.supply,confidence<.48?20:10);p.infrastructure=q(p.infrastructure,confidence<.48?20:10);p.resistance=q(p.resistance,confidence<.48?20:10)}
for(const s of out.strategicSites||[]){const c=out.countries?.[s.countryId];if(c?.controller===observerController)continue;s.health=q(s.health,confidence<.48?25:10)}
out.navalTaskForces=(out.navalTaskForces||[]).filter(tf=>tf.owner===observerController||tf.mission!=='silent'||confidence>=.58);for(const tf of out.navalTaskForces){if(tf.owner===observerController)continue;tf.surface=q(tf.surface,confidence<.48?3:confidence<.72?2:1);tf.carriers=q(tf.carriers,confidence<.62?2:1);tf.submarines=q(tf.submarines,confidence<.48?3:confidence<.72?2:1);tf.readiness=q(tf.readiness,confidence<.48?25:10);tf.supply=q(tf.supply,confidence<.48?25:10)}
out.intelView={redacted:true,confidence:Number(confidence.toFixed(2)),navalContacts:(out.navalTaskForces||[]).filter(tf=>tf.owner!==observerController).length};return out}
